kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jwenneberg/nginx-backend:0.0.1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: backend
