apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: site2
namePrefix: prod-

resources:
  - namespace.yml
  - ../../base

components:
  - ../../variants/prod

patches:
  - path: configmap.yml
  # - path: version.yml
