apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsite
namePrefix: dev-

resources:
  - namespace.yml
  - ../../base

components:
  - ../../variants/dev

patches:
  - path: configmap.yml
  - path: version.yml
