apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
spec:
  generators:
  - list:
      elements:
        - cluster: dev
          url: https://kubernetes.default.svc
        - cluster: prod
          url: https://kubernetes.default.svc
      # - cluster: engineering-dev
      #   url: https://1.2.3.4
      # - cluster: engineering-prod
      #   url: https://2.4.6.8
      # - cluster: finance-preprod
      #   url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-app-set'
    spec:
      project: proj-site1
      source:
        repoURL: https://github.com/wenneberg6/homelab.git
        targetRevision: HEAD
        path: applicationSet/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}app-set'