apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-multienv
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wenneberg6/homelab.git
    targetRevision: HEAD
    path: app/overlays/devsite1
  destination:
    server: https://kubernetes.default.svc
    namespace: devsite1