apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-multienv-site1
  namespace: argocd
spec:
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
  project: default
  source:
    repoURL: https://github.com/wenneberg6/homelab.git
    targetRevision: HEAD
    path: app/overlays/site1
  destination:
    server: https://kubernetes.default.svc
    namespace: site1
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: true 